{{- range .Values.vaultPolicies }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  policyName: {{ .data.policyName | quote }}
  policyData: | {{ .data.policyData | trim | nindent 4 }}
---
{{- end }}
